# Generated by Django 2.2.1 on 2019-05-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.Country'),
        ),
    ]
