# Generated by Django 2.2.1 on 2019-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20190519_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
